name: EggBuff
version: '${version}'
main: com.ryd.eggbuff.EggBuff
api-version: '1.20'
authors: [Ryd]
description: "Acts as a portable beacon for the player to select primary and secondary effects."
website: https://github.com/Not-ryd
